version: "3.9"

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=django_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
    ports:
      - "5432:5432" # Опционально

  redis:
    image: redis:7-alpine
    container_name: redis_broker

  django:
    build: ./django_api
    container_name: django_api
    volumes:
      - ./django_api:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - POSTGRES_DB=django_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - DB_HOST=db
      - DB_PORT=5432
      # Не забудьте про Celery, раз мы его обсуждали
      - CELERY_BROKER_URL=redis://redis:6379/0
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_TOKEN}
      - DJANGO_SUPERUSER_USERNAME=${DJANGO_SUPERUSER_USERNAME}
      - DJANGO_SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD}
      - DJANGO_SUPERUSER_EMAIL=${DJANGO_SUPERUSER_EMAIL}
      - YOOKASSA_API_KEY=${YOOKASSA_API_KEY}
      - YOOKASSA_SHOP_ID=${YOOKASSA_SHOP_ID}

  # Новый сервис: Воркер, который будет создавать конфиги на серверах
  celery_worker:
    build: ./django_api
    container_name: celery_worker
    command: celery -A backend worker --loglevel=info
    volumes:
      - ./django_api:/app
    depends_on:
      - django
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0

  bot:
    build: ./bot
    container_name: aiogram_bot
    command: watchfiles --filter python "python main.py"
    volumes:
      - ./bot:/app
    depends_on:
      - django
    environment:
      - API_URL=http://django:8000
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - WEB_APP_URL=${WEB_APP_URL}
      - DJANGO_SUPERUSER_USERNAME=${DJANGO_SUPERUSER_USERNAME}
      - DJANGO_SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD}

  miniapp:
    build: ./miniapp
    container_name: nextjs_app
    command: npm run dev
    volumes:
      - ./miniapp:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - django
    environment:
      - BOT_TOKEN=${TELEGRAM_TOKEN}
      - DJANGO_API_URL=${DJANGO_API_URL}
      - DJANGO_SUPERUSER_USERNAME=${DJANGO_SUPERUSER_USERNAME}
      - DJANGO_SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD}
      - TELEGRAM_BOT_URL=${TELEGRAM_BOT_URL}
      - TARIFFS=${TARIFFS}
volumes:
  postgres_data:
